### ISSUE TITLE
Issue PolkaBTC - BTC OP_RETURN Payment (Electrum Wallet) -   Default Amount decimal place is out 3

### ISSUE THREAD

**Issue by s3cryptostuff** [interlay/polkabtc-ui#1]
If you use the "Copy" button to paste the pay amount into electrum, the decimal place on the amount is out 3 places.
ie if I requested .004565 PolkaBTC, then the payment amount in the copy shows 4.656

This help documentation prides good examples, but I received a few insufficient amount errors from Electrum wallet until I noticed
that the amount was off.

Keep up the good work. I appreciate all of the development effort

**Comment by alexeiZamyatin** [comment]
Thanks for the feedback!

Electrum and many Bitcoin wallets use mBTC as base denomination (mBTC = BTC * 1000). 
In the Issue dialogue, we display the amounts both in BTC and mBTC, but the "copy" button for Electrum uses the mBTC format to match Electrum.  

We'll try to make this more clear / adding a note to the user guide!

**Comment by s3cryptostuff** [comment]
[PolkaBTC-Default-pay.pdf](https://github.com/interlay/polkabtc-ui/files/5570053/PolkaBTC-Default-pay.pdf)


> 
> 
> Thanks for the feedback!
> 
> Electrum and many Bitcoin wallets use mBTC as base denomination (mBTC = BTC * 1000).
> In the Issue dialogue, we display the amounts both in BTC and mBTC, but the "copy" button for Electrum uses the mBTC format to match Electrum.
> 
> We'll try to make this more clear / adding a note to the user guide!

**Comment by s3cryptostuff** [comment]
Thanks! 
I default to BTC in wallet display so it looks like I am more of a bitcoin whale. haha
Cheers

**Comment by alexeiZamyatin** [comment]
Right, we'll add a more clear note that it's in mBTC. Thanks for reporting! 
We're replacing OP_RETURN so it will be much earsier to use in the next version.

**Comment by nud3l** [comment]
Thanks for reporting this We added a note in the issue wizard:

![image](https://user-images.githubusercontent.com/14966470/100625595-14973000-3368-11eb-805c-7b145203190b.png)

Closing this issue for now.
