### ISSUE TITLE
oracle offline

### ISSUE THREAD

**Issue by Edyzero** [interlay/polkabtc-ui#109]
**Describe the bug**
When redeeming polkbtc, it fails and gives an error message security.parachain.oracle.offline

**Expected behavior**
polkbtc redemption fails

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Smartphone (please complete the following information):**
 - Version 88

**Comment by savudani8** [comment]
This error is due do our oracle services being unreachable because of load, and it is now fixed. We are currently working on improving the reliability of the system, but this was not a problem related to this repository.
