### ISSUE TITLE
Negative value is getting filled in Issue/redeem/transfer section

### ISSUE THREAD

**Issue by rahul1031pathak** [interlay/polkabtc-ui#121]
![Screenshot (101)](https://user-images.githubusercontent.com/25725473/110232624-d00dc880-7f44-11eb-93f1-d120d1e69887.png)
![Screenshot (102)](https://user-images.githubusercontent.com/25725473/110232627-d1d78c00-7f44-11eb-8534-f970fe32e5c7.png)

**Steps To Reproduce**
1. Go to issue/redeem/transfer
2. Try to enter negative value 
3. User is able to enter negative value

**Expected behavior**
Negative value should not be allowed

**Screenshots**

**Desktop (please complete the following information):**

**Comment by savudani8** [comment]
Thank you for pointing out this bug! This is a duplicate of https://github.com/interlay/polkabtc-ui/issues/116 and as such I will close this. Please follow that issue for updates
