### ISSUE TITLE
Incorrect confirmation value is showing when user clicks on I have made payment without bitcoin transaction confirmations

### ISSUE THREAD

**Issue by rahul1031pathak** [interlay/polkabtc-ui#124]
**To Reproduce**
1. Go to issue section , initiate a issue request
2. You will be asked to make payment to a bitcoin address , do the payment 
3. Without the confirmation on bitcoin network , click **I have made payment** 
4. See below , confirmation value is showing 1.
5. Go to request detail page , claim polkabtc button is active 

**Expected behavior**
Confirmation should not show 1 ,claim button should not be active

**Screenshots**
![Screenshot (105)](https://user-images.githubusercontent.com/25725473/110233912-5a5a2a80-7f4d-11eb-9605-152f87012ac5.png)
![Screenshot (106)](https://user-images.githubusercontent.com/25725473/110233913-5c23ee00-7f4d-11eb-8ebb-b94bc8b158a5.png)
![Screenshot (107)](https://user-images.githubusercontent.com/25725473/110233914-5cbc8480-7f4d-11eb-97bb-5509f4d6406e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nud3l** [comment]
Thanks for the bug report. We closed this in #148
