### ISSUE TITLE
Redeem transaction is pending from more than 20 hours , No way to speed it up or even cancel

### ISSUE THREAD

**Issue by rahul1031pathak** [interlay/polkabtc-ui#125]
**To Reproduce**
1. **_Redeem request is pending from last 20 hours_** 
2.  REQUEST #89B807633D26BE93467EC7C653F21F283F5FDE049B7B90F5023A2ED459E9460D

**Expected behavior**
**_Either request should get completed or
User should have option to cancel the request or speed up_** 

**Screenshots**

![Screenshot (108)](https://user-images.githubusercontent.com/25725473/110235563-bbd2c700-7f56-11eb-90e1-99c6849ce4af.png)
<img width="960" alt="Screenshot (109)" src="https://user-images.githubusercontent.com/25725473/110235565-bd03f400-7f56-11eb-923f-e956ff56de95.png">

**Comment by savudani8** [comment]
This bug is caused by Vault clients not retrying to execute requests. As the latest vault version should fix this, please try again and update here as appropriate

**Comment by rahul1031pathak** [comment]
If for any reason redeem request is pending User should be able to cancel it .
User experience will not be good if their assets is in pending state and he can not any thing .

**Comment by nud3l** [comment]
Hi! The redeem period is not set to 24 hours. If the vault does not fulfil the request after 24 hours, you will be able to either retry or burn. See more details here: https://docs.polkabtc.io/#/start/faq?id=what-happens-if-a-vault-does-not-fulfill-the-redeem-request-within-24-hours
