### ISSUE TITLE
Could not connect Parachain

### ISSUE THREAD

**Issue by i945** [interlay/polkabtc-ui#126]
When I use "ISSUE", it tells me "Could not connect Parachain", so I can't get the transfer address. I noticed that my DOT fee has been reduced. So how should I proceed to the next step.

I have tried:
-Use global SSR
-Fix the network
-Change browser

**Comment by savudani8** [comment]
The parachain was stalled from processing requests at certain points last week to ensure it only runs within certain security parameters. This should be fixed and not happen again - please check and update this issue
