### ISSUE TITLE
Redeem transaction is pending from more than 8hrs

### ISSUE THREAD

**Issue by biggwb** [interlay/polkabtc-ui#157]
1.  Redeem request is pending from last 20 hours
    2.  Request id #5bc6f6f315257cada479fb2fbe34cfe367b8d3ba7e0677426184dfdf6bf72a0a
   
Expected behavior
Either request should be completed or should have option to cancel the request or speed up transaction.

Should have some way of seeing whats going on, on the blockchain like viewing an explore to see how much time is left to complete the block.
Screenshots

**Screenshots**

![Screen Shot 2021-03-12 at 7 43 51 PM](https://user-images.githubusercontent.com/41408770/111013987-ac48e900-836f-11eb-84de-1cc06cc689d1.jpeg)

**Desktop (please complete the following information):**
 - Mac OS 11.2
 
 - Browser chrome ]
 - Version Version 88.0.4324.192 (Official Build) (x86_64)

**Additional context**

**Comment by biggwb** [comment]
Still having the same problem as before see the previous post.
I have tried to redeem 3 more times still cannot get to redeem see attachment.
and the last post was 11hrs ago still pending.


Request id #fb903ed85cd8d929b990cae5be76fb54bddd2abd5a34e7b19f22ce34744f7545

**Comment by biggwb** [comment]
Still having the same problem as before see the previous post.
I have tried to redeem 3 more times still cannot get to redeem see attachment.
and the last post was 11hrs ago still pending.

Request id #fb903ed85cd8d929b990cae5be76fb54bddd2abd5a34e7b19f22ce34744f7545

<img width="850" alt="Screen Shot 2021-03-19 at 11 25 42 PM" src="https://user-images.githubusercontent.com/41408770/111857911-31517680-890b-11eb-814d-8127635933a5.png">

**Comment by biggwb** [comment]
Is there a way you can put in a feature to cancel the REDEEM transaction? to reclaim PolkaBTC if it gets stuck.

**Comment by nud3l** [comment]
Hi! We have set the redeem period to 24 hours again. You should be able to either retry or burn your PolkaBTC now.
