### ISSUE TITLE
Leaderbord dead nodes

### ISSUE THREAD

**Issue by jlllk** [interlay/polkabtc-ui#158]
Hello! I see my node in the vault leaderboard.

5EeQqU4hHNDHiPcgRJHb5q7hU3WsRx5R7SwEBXmzJf8nkuNF  SLA score 6.44 right now. I have a screenshot. But I turned off this node a few days ago. I did it before the challenge 2 started. 

How is this possible?

**Comment by nud3l** [comment]
When your vault is offline, its account is still registered on the parachain. Vaults don't need to be online to accept new issue requests and this is purely decided on the parachain level. In your case, the vault might be assigned an issue request that then was leading to an increase in the SLA.
