### ISSUE TITLE
Unable to reach more info about challenges 

### ISSUE THREAD

**Issue by EricRanasinghe** [interlay/polkabtc-ui#294]
**Description**
I am unable to reach page with more information about the interesting challenges I want to participate in ;(

**To Reproduce**
1. Go to https://bridge.interlay.io/challenges
2. Click on 'More Info'
3. See 404 error

**Desktop**
 - OS: macOS Big Sur
 - Browser: Brave
 - Version: 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)

**Screenshot**
<img width="1438" alt="Screenshot 2021-09-13 at 23 12 52" src="https://user-images.githubusercontent.com/11922932/133150961-1f1232c8-7825-4fd5-9db2-b816198521f8.png">

**Comment by nud3l** [comment]
We removed challenges for now.
