### ISSUE TITLE
Wrong app link in "About" section of this repo

### ISSUE THREAD

**Issue by andrii-bil** [interlay/polkabtc-ui#295]
**To Reproduce**
1. Open polkabtc-ui repo (https://github.com/interlay/polkabtc-ui).
2. In "About" section click on bridge app link.

**Expected behavior**
User is redirected to valid URL where bridge app is deployed.
Expected URL - bridge.interlay.io/

**Actual behavior**
Application does not open. "Error 526 Invalid SSL certificate".
Actual URL - bridge.interbtc.io/

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser: Chrome 
 - Version: 93.0.4577.63

**Comment by nud3l** [comment]
Thanks - fixed!
