### ISSUE TITLE
DOT Faucet on site doesn't transfer tokens

### ISSUE THREAD

**Issue by antonva** [interlay/polkabtc-ui#51]
Having followed the getting started guide and funded my BTC testnet wallet I ran into this issue on https://beta.polkabtc.io/
```
Funding failed. You can only use the faucet once every 6 hours. 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
I created a new account for PolkaBTC and selected it from the dropdown in the top right.
After clicking the `DOT faucet` link it waits a while and then shows this message.

I have gone through all available accounts and none show any available DOT tokens on the site.

**Comment by nud3l** [comment]
Thanks for the bug report. Confirmed and we are investigating this right now.

**Comment by KyrinCode** [comment]
Same problem here, and also meet "Could not connect to the Parachain" from both Chrome and Brave
![image](https://user-images.githubusercontent.com/30864546/109669276-e9152300-7bac-11eb-9703-6406ad9c8ccd.png)

**Comment by EthanPhan** [comment]
Same issue. Had to use the faucet on discord

**Comment by gregdhill** [comment]
We had some load issues which I think are now mostly resolved. @antonva do you happen to have the response for the JSON parsing issue?

**Comment by antonva** [comment]
@gregdhill I didn't think to jot it down, I don't have it.

**Comment by gregdhill** [comment]
No worries, I'll close this issue for now. Feel free to re-open if you encounter the issue again.
