### ISSUE TITLE
Send too little BTC when minting PolkaBTC

### ISSUE THREAD

**Issue by XL-ii** [interlay/polkabtc-ui#57]
Send too little BTC when minting PolkaBTC.This issues has been submitted in discord

**Comment by nud3l** [comment]
# Problem 

When a user sends too little BTC to a vault, the BTC are kept with the vault and no PolkaBTC can be minted.

# Expected behavior

Either the BTC should be transferred back to the user OR a smaller amount corresponding to the transferred BTC should be minted.

**Comment by nud3l** [comment]
We added a feature that users can send too little BTC. See #11
