### ISSUE TITLE
Misleading error message when 0 balance

### ISSUE THREAD

**Issue by aamironov** [interlay/polkabtc-ui#70]
**Describe the bug**
If I try to redeem some BTC when balance is 0 then I am getting error "Please enter an amount smaller than your current balance: 0"

**To Reproduce**
1. Go to redeem when balance 0
2. Enter any number

**Expected behavior**
"Insufficient balance to transfer." as on the transfer page.

**Screenshots**
<img width="1280" alt="Screen Shot 2021-03-02 at 11 13 25 AM" src="https://user-images.githubusercontent.com/16032708/109702378-01ebed00-7b49-11eb-82b0-b14ddef6354b.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nud3l** [comment]
Resolved in the latest release.
