### ISSUE TITLE
Issue's request page has different decimal numbers

### ISSUE THREAD

**Issue by aamironov** [interlay/polkabtc-ui#72]
**Describe the bug**
Request page:
0.00012345 PolkaBTC
Bridge fee 0 BTC
Total Deposit 0.00012 BTC
Send 0.00012407  BTC
See the screenshot

**To Reproduce**
1. Create issue with 0.00012344567890 BTC
2. Open request

**Expected behavior**
Total deposit=send value=PolkaBTC+Bridge Fee

**Screenshots**
<img width="1280" alt="Screen Shot 2021-03-02 at 11 26 15 AM" src="https://user-images.githubusercontent.com/16032708/109704053-04e7dd00-7b4b-11eb-9b05-69e17f1d067c.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by savudani8** [comment]
Fixed in https://github.com/interlay/polkabtc-ui/pull/84
