### ISSUE TITLE
ISSUE REQUEST: Transaction not confirmed

### ISSUE THREAD

**Issue by repetny** [interlay/polkabtc-ui#73]
**Describe the bug**
When requesting to issue PolkaBTC, the transaction shows not confirmed in app while confirmed on blockstream.

**To Reproduce**
1. Go to 'https://beta.polkabtc.io/app'
2. Select PolkaBTC amount, click confirm and send tBTC to the address.
3. Scroll down to 'Issue requests' with created transaction showing "Confirmations 0"
4. https://blockstream.info/testnet/tx/37a91a16baccb5a4b9e95b22f97a7ccb93f89afb37de48ac1ffad08e41f2e9e4 shows confirmed transaction
5. 20mins later it shows confirmed in app (tried to reload the app before multiple times)

**Expected behavior**
See confirmed transaction sooner than 20 minutes later in app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Firefox
 - Version 86.0

**Smartphone (please complete the following information):**
 - 
![obrazek](https://user-images.githubusercontent.com/13663163/109712083-dd6f2f80-7b9f-11eb-8bf2-28a18b9518d0.png)

**Additional context**

**Comment by savudani8** [comment]
For your security, we count block confirmations differently than block explorers. The explorers consider a block in the mining pool but which is not yet appended to the blockchain to have 1 confirmation, whereas we consider that to have 0 confirmations. We have fixed the display discrepancy to avoid confusion: https://github.com/interlay/polkabtc-stats/pull/20

**Comment by repetny** [comment]
Makes sense. Thank you and keep up the good work! :)
