### ISSUE TITLE
Minting takes too long to confirm

### ISSUE THREAD

**Issue by EthanPhan** [interlay/polkabtc-ui#75]
**Describe the bug**
After I sign the message to confirm the deposit the waiting screen stays for more than 15 minutes.

The waiting screen:
<img width="642" alt="Screenshot 2021-03-03 at 8 30 15 AM" src="https://user-images.githubusercontent.com/21288521/109734485-07563f80-7bfc-11eb-8e72-55c8e63b7f1e.png">

When I refreshed the webpage to mint again I got the following error:

<img width="830" alt="Screenshot 2021-03-03 at 8 37 36 AM" src="https://user-images.githubusercontent.com/21288521/109734546-23f27780-7bfc-11eb-9ffd-e78263da6cad.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.1 Big Sur
 - Browser Brave 1.20.110
 - Version 1.20.110

**Comment by savudani8** [comment]
Thanks for reporting this. We had some system scalability issues during the beta launch and we are working on removing all identified bottlenecks. The minting should be quicker, but expect this to improve in the future. This is not a UI bug, however
