### ISSUE TITLE
NOT able to mint 1:1 polkabtc

### ISSUE THREAD

**Issue by rjramesh** [interlay/polkabtc-ui#82]
**Describe the bug**
i am not able to mint 1:1 polkabtc 
i was send btc on issue adddres and transction success but minting not work
errror show btcrelay insuffucient value value request below
**To Reproduce**
1. Go to isssue tab enter value we wants i set 1 polkabtc
2. Click on confirm
3. Scroll down to and see issue address which we have send btc and i was send btc on that
4. i see error 1:1 polkabtc was not mint see error showing,. btcrelay insuffucient value value request below
![Screenshot (765)](https://user-images.githubusercontent.com/33414006/109849291-38c02100-7c77-11eb-9584-36d226eca8e5.png)

**Expected behavior**
we need to mint 1:1 polkabtc when i send 1 btc success on issue address

**Screenshots**
![Screenshot (764)](https://user-images.githubusercontent.com/33414006/109849785-c7cd3900-7c77-11eb-80c3-275de28f06be.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [brave]
 - Version [64 bit]

**Additional context**
some error showing in deposits and claiming process and transction will not confirm fast not reflect

**Comment by savudani8** [comment]
The Bitcoin value you need to deposit includes a fee for the vault that processes your PolkaBTC issuance. As you can see in both screenshots, right below the 1 BTC amount there are two rows called "Bridge Fee" and "Total Deposit". It is the total deposit you need to submit as a bitcoin transaction, as is explained in the issue flow. So the minting is 1:1 but you need to also pay for the bridge fee
