### ISSUE TITLE
previous transction history all clear not seen

### ISSUE THREAD

**Issue by rjramesh** [interlay/polkabtc-ui#83]
**Describe the bug**
when i send btc to issue address then i resfresh tab and all previos history not seen

**To Reproduce**
1. Go to issue tab 
2. Click on refresh button
3. Scroll down to walllet connected 
4. See error to our last transction history not seen or fetch

**Expected behavior**
all history of all transaction need to see at below but not seen

**Screenshots**
![Screenshot (769)](https://user-images.githubusercontent.com/33414006/109856765-dd466100-7c7f-11eb-8cab-549790bf69db.png)

![Screenshot (768)](https://user-images.githubusercontent.com/33414006/109856892-0961e200-7c80-11eb-98a6-c7d97f9bfe01.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [brave]
 - Version [64 bit]

**Additional context**
we need to see all last transaction and claim button available in history

**Comment by savudani8** [comment]
You may have reuested to issue with one Polkadot account and then switched to a different account. The history only shows requests related to the Polkadot account selected in the top-right of the page, in the topbar.
